---
title: "Testing of SWMPrExtension"
author: "Dave Eslinger"
date: "2/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

Just a spot to save code bits to be run from within the SWMPrExtension package

## Seasonal_barplot labels

Labels are not correct for long time series.

```{r seasonal_barplot}
library(SWMPrExtension)
library(here)
load(here("../SWMPrExtension_TESTING/data/job_met.rda"))
seasonal_barplot(dat, param = param, 
                 hist_rng = hist_rng, 
                 season_grps = season_grps, 
                 season_names = season_names, 
                 hist_avg = T, 
                 log_trans = F, 
                 converted = F, 
                 season_facet = T, 
                 plot_title = T)
```

I want different hlines on faceted plots
```{r working_hline_on_facets}
library(tidyverse)
gr <- sym("gear")

dMean <- mtcars %>%
    group_by(!!gr) %>%
    summarise(MN = mean(cyl))
ggplot(mtcars) +
    geom_point(aes(mpg, cyl)) +
    geom_hline(data = dMean, aes(yintercept = MN)) +
    facet_wrap(gr)

(p1 <- ggplot(mtcars) +
    geom_point(aes(mpg, cyl)))
(p2 <- p1 +
     geom_hline(data = dMean, aes(yintercept = MN)))
 
(p3 <- p2 +
    facet_wrap(gr))


(bp1 <- ggplot(data = mtcars, aes(x = cyl, y = mpg, fill = gear)) +
    geom_bar(stat = "count", position = "stack"))
(bp2 <- bp1 +
     geom_hline(data = dMean, aes(yintercept = MN)))
 
(bp3 <- bp2 +
    facet_wrap(gr))

```


```{r jobos_hline}
load(here("../SWMPrExtension_TESTING/data/job_totprcp_dat_hist.rda"))
foo <- ungroup(job_totoprcp_dat_hist)

# ggplot(data = dat_hist, aes_(x = yr, y = res, fill = seas)) +
#       geom_bar(stat = "identity", position = bar_position) 
ggplot() +# data = foo, 
       # aes(x = year, y = result, fill = season)) +
      # geom_bar(stat = "identity", position = "stack") +
      geom_col(data = foo,aes(x = year, y = result, fill = season), position = "stack") +
  facet_wrap(~ season)
  
ggplot() +
      geom_point(data = foo, aes(x = year, y = result, color = season),
               stat = "identity")
```

```{r}
bar_seas +
        facet_wrap(seas, ncol = 1)
```

